namespace BugZapperLabs.RipSharp.Core;

public class RipOptions
{
    public string Disc { get; set; } = "disc:0";
    public string Output { get; set; } = string.Empty;
    public string? Temp { get; set; }
    public bool Tv { get; set; }
    public bool AutoDetect { get; set; } = true; // Auto-detect content type by default
    public string? Title { get; set; }
    public int? Year { get; set; }
    public int Season { get; set; } = 1;
    public int EpisodeStart { get; set; } = 1;
    public bool Debug { get; set; }
    public string? DiscType { get; set; } // dvd|bd|uhd
    public bool ShowHelp { get; set; }
    public bool ShowVersion { get; set; }
    public bool TempWasAutoGenerated { get; set; }
    public bool EnableParallelProcessing { get; set; } = true; // Enable parallel rip and encode by default

    public static RipOptions ParseArgs(string[] args)
    {
        var opts = new RipOptions();

        if (args.Any(a => a == "-v" || a == "--version"))
        {
            opts.ShowVersion = true;
            return opts;
        }

        // Check for help first
        if (args.Length == 0 || args.Any(a => a == "-h" || a == "--help"))
        {
            opts.ShowHelp = true;
            return opts;
        }

        for (int i = 0; i < args.Length; i++)
        {
            var a = args[i];
            string? next() => i + 1 < args.Length ? args[++i] : null;
            switch (a)
            {
                case "--disc": opts.Disc = next() ?? opts.Disc; break;
                case "--output": opts.Output = next() ?? opts.Output; break;
                case "--temp": opts.Temp = next(); break;
                case "--tv": opts.Tv = true; opts.AutoDetect = false; break;
                case "--mode":
                    var mode = next();
                    if (mode == null)
                        throw new ArgumentException("--mode requires a value");
                    var modeLower = mode.ToLowerInvariant();
                    if (modeLower == "tv" || modeLower == "series")
                    {
                        opts.Tv = true;
                        opts.AutoDetect = false;
                    }
                    else if (modeLower == "movie" || modeLower == "film")
                    {
                        opts.Tv = false;
                        opts.AutoDetect = false;
                    }
                    else if (modeLower == "auto" || modeLower == "detect")
                    {
                        opts.AutoDetect = true;
                    }
                    else throw new ArgumentException("--mode must be 'movie', 'tv', or 'auto'");
                    break;
                case "--title": opts.Title = next(); break;
                case "--year": if (int.TryParse(next(), out var y)) opts.Year = y; break;
                case "--season": if (int.TryParse(next(), out var s)) opts.Season = s; break;
                case "--episode-start": if (int.TryParse(next(), out var e)) opts.EpisodeStart = e; break;
                case "--debug": opts.Debug = true; break;
                case "--disc-type": opts.DiscType = next(); break;
                case "--sequential": opts.EnableParallelProcessing = false; break;
            }
        }
        if (string.IsNullOrWhiteSpace(opts.Output))
        {
            throw new ArgumentException("--output is required");
        }
        if (string.IsNullOrEmpty(opts.Temp))
        {
            opts.Temp = Path.Combine(opts.Output, GetTempDirectoryName());
            opts.TempWasAutoGenerated = true;
        }
        return opts;
    }

    private static string GetTempDirectoryName()
    {
        return $".{Path.GetFileNameWithoutExtension(Path.GetRandomFileName())}";
    }

    public static void DisplayHelp(IConsoleWriter writer)
    {
        const int optionWidth = 26;
        var detailIndent = new string(' ', 4 + optionWidth + 1);

        void OptionLine(string option, string description)
        {
            writer.Highlight($"    {option.PadRight(optionWidth)} {description}");
        }

        void OptionDetail(string description)
        {
            writer.Muted($"{detailIndent}{description}");
        }

        writer.Accent("ripsharp - DVD/Blu-Ray/UHD disc ripping tool");
        writer.Plain("");
        writer.Accent("USAGE:");
        writer.Plain("    ripsharp (OPTIONS)");
        writer.Plain("");
        writer.Accent("REQUIRED OPTIONS:");
        OptionLine("--output PATH", "Output directory for ripped files");
        writer.Plain("");
        writer.Accent("OPTIONS:");
        OptionLine("--mode auto|movie|series", "Content type detection (default: auto)");
        OptionDetail("- auto: Automatically detect movie vs series");
        OptionDetail("- movie: Treat as single movie");
        OptionDetail("- series: Treat as series");
        OptionLine("--disc PATH", "Optical drive path (default: disc:0)");
        OptionLine("--temp PATH", "Temporary ripping directory");
        OptionDetail("Default: {output}/<RANDOM_STRING>");
        OptionLine("--title TEXT", "Custom title for file naming");
        OptionLine("--year YYYY", "Release year (movies only)");
        OptionLine("--season N", "Season number (TV only, default: 1)");
        OptionLine("--episode-start N", "Starting episode number (TV only, default: 1)");
        OptionLine("--disc-type TYPE", "Override disc type: dvd|bd|uhd");
        OptionDetail("Default: auto-detect");
        OptionLine("--sequential", "Disable parallel processing");
        OptionDetail("Rip all, then encode all");
        OptionLine("--debug", "Enable debug logging");
        OptionLine("-h, --help", "Show this help message");
        OptionLine("-v, --version", "Show the application version");
        writer.Plain("");
        writer.Accent("EXAMPLES:");
        writer.Muted("    # Rip with auto-detection (recommended)");
        writer.Plain("    ripsharp --output ~/Movies --title \"The Matrix\" --year 1999");
        writer.Plain("");
        writer.Muted("    # Rip a movie (explicit)");
        writer.Plain("    ripsharp --output ~/Movies --mode movie --title \"The Matrix\" --year 1999");
        writer.Plain("");
        writer.Muted("    # Rip a series season (explicit)");
        writer.Plain("    ripsharp --output ~/Series --mode series --title \"Breaking Bad\" --season 1");
        writer.Plain("");
        writer.Muted("    # Use second disc drive");
        writer.Plain("    ripsharp --output ~/Movies --disc disc:1");
        writer.Plain("");
        writer.Accent("ENVIRONMENT VARIABLES:");
        writer.Highlight("    TMDB_API_KEY    TMDB API key for metadata lookup (recommended)");
        writer.Highlight("    TVDB_API_KEY    TVDB API key for metadata lookup (optional)");
        writer.Highlight("    OMDB_API_KEY    OMDB API key for metadata lookup (optional)");
        writer.Plain("");
        writer.Muted("For more information, visit: https://github.com/mapitman/ripsharp");
    }
}
